import postgres from "postgres";
import { indexerEngine } from "../indexer";
import { dataStore } from "../store";

const dbUrl = process.env.DATABASE_URL;
if (!dbUrl) {
  console.error("DATABASE_URL missing in .env");
  process.exit(1);
}

const sql = postgres(dbUrl);

async function cleanTestData() {
  console.log("=================================================");
  console.log("🧹 CLEANING UP DATABASE FROM UNIT TESTING DATA");
  console.log("=================================================");

  // 1. Clear in-memory store
  dataStore.proposals.clear();
  dataStore.donations.clear();
  dataStore.batches.clear();

  // 2. Clean fake/test proposals (Keep only authentic on-chain proposals #1, #2, #3, #4)
  console.log("1. Cleaning test proposals...");
  await sql`
    DELETE FROM disbursement_proposals
    WHERE proposal_id_on_chain > 4 
       OR beneficiary_name IN ('Pak Joko Suwarno', 'Ibu Aminah', 'Ibu Maryam', 'Pak Supardi', 'Ahmad Santri', 'Pak Rahmat', 'Ibu Siti', 'Ahmad', 'Fulan', 'Ibu Nurhayati', 'Bpk. Target Batal', 'Ahmad Dahlan', 'Rian Pratama', 'Pesantren Al-Ikhlas', 'Pak Slamet');
  `;

  // 3. Clean test donations (Keep only authentic USDC on-chain donations)
  console.log("2. Cleaning test donations...");
  await sql`
    DELETE FROM donations
    WHERE trx_id LIKE 'TRX-TEST-%' 
       OR trx_id LIKE 'TRX-20260904-5508'
       OR donor_name LIKE '%Test%';
  `;

  // 4. Clean fake merkle batches generated by tests
  console.log("3. Cleaning test merkle batches...");
  await sql`
    DELETE FROM merkle_batches;
  `;

  // Insert the authentic on-chain settled batch (Batch 345097)
  await sql`
    INSERT INTO merkle_batches (batch_number, merkle_root, total_amount_idr, item_count, tx_hash, status, settled_at)
    VALUES (
      345097,
      '0x8b926f1457b19b6b56ae010d1fefa7012ee61e25170b2e56f92e0cc22684a593',
      25000000,
      10,
      '0xe2334d7752221e8702ddc188ae878ead2ac521800fd8efb9ddbf26aa545873aa',
      'settled_onchain',
      NOW()
    )
    ON CONFLICT (batch_number) DO NOTHING;
  `;

  // 5. Clean test onchain events
  console.log("4. Cleaning mock/test onchain events...");
  await sql`
    DELETE FROM onchain_events
    WHERE tx_hash LIKE '%mock%' 
       OR tx_hash LIKE '%test%'
       OR tx_hash = '0x9a8f7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a';
  `;

  // 6. Reset and re-sync indexer from startBlock 304590800
  console.log("5. Re-syncing indexer from Arbitrum Sepolia on-chain events...");
  await sql`
    UPDATE indexer_state
    SET last_indexed_block = 304590800, status = 'SYNCING'
    WHERE indexer_key = 'sepolia_zakat_l1' OR indexer_key = 'arbitrum_sepolia_zakat_l1';
  `;

  try {
    let syncRes = await indexerEngine.syncOnce();
    console.log(`Synced blocks ${syncRes.fromBlock} - ${syncRes.toBlock}, processed ${syncRes.eventsProcessed} events.`);
  } catch (e: any) {
    console.warn("Indexer sync warning:", e.message || e);
  }

  // 7. Verify final counts
  console.log("\n=== FINAL DATABASE STATE ===");
  const [proposals] = await sql`SELECT count(*) FROM disbursement_proposals;`;
  const [donations] = await sql`SELECT count(*) FROM donations;`;
  const [batches] = await sql`SELECT count(*) FROM merkle_batches;`;
  const [events] = await sql`SELECT count(*) FROM onchain_events;`;
  const [auditors] = await sql`SELECT count(*) FROM auditor_profiles;`;

  console.log(`- Disbursement Proposals : ${proposals.count}`);
  console.log(`- Donations              : ${donations.count}`);
  console.log(`- Merkle Batches         : ${batches.count}`);
  console.log(`- Onchain Events         : ${events.count}`);
  console.log(`- Auditor Profiles       : ${auditors.count}`);

  console.log("\nProposals list:");
  const pList = await sql`SELECT proposal_id_on_chain, beneficiary_name, asnaf_category, amount, status, audit_status FROM disbursement_proposals ORDER BY proposal_id_on_chain ASC;`;
  console.log(pList);

  console.log("\nDonations list:");
  const dList = await sql`SELECT trx_id, donor_name, amount_idr, status, payment_method FROM donations ORDER BY id ASC;`;
  console.log(dList);

  await sql.end();
  console.log("\n✅ Database is now completely clean from test artifacts!");
}

cleanTestData().catch((err) => {
  console.error("Cleanup error:", err);
  process.exit(1);
});
