/** Regenerate the public synthetic Solidity fixture against the pinned proving key. */
import { getPoseidon, contributionContext, toField, toFieldHex, type BatchItemWitness } from "../zk-batch-store";
import { createZkProofService } from "../zk-proof-service";
import { keccak256 } from "viem";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
const poseidon = await getPoseidon();
const hash = (values: bigint[]) => BigInt(poseidon.F.toString(poseidon(values)));
const institutionKey = toField(keccak256(Buffer.from("lpz-sinar-amanah")));
const context = contributionContext("contrib-sinar-001", 1, 1, 1);
const purposeHash = toField(keccak256(Buffer.from("Synthetic fixture only")));
const leaf = hash([context, 5000000n, 42n, 0n, purposeHash]);
let layers = [leaf, ...Array<bigint>(15).fill(0n)];
const pathElements: string[] = [];
for (let level = 0; level < 4; level++) {
  pathElements.push(layers[1].toString());
  layers = Array.from({ length: layers.length / 2 }, (_, i) => hash([layers[i * 2], layers[i * 2 + 1]]));
}
const witness: BatchItemWitness = {
  contributionId: "contrib-sinar-001", institutionId: "lpz-sinar-amanah", batchNumber: 1, batchVersion: 1, version: 1,
  batchRoot: layers[0].toString(), receiptCommitment: hash([institutionKey, context, leaf]).toString(),
  institutionKey: institutionKey.toString(), contributionIdHash: context.toString(), fundType: 0,
  amount: "5000000", salt: "42", purposeHash: purposeHash.toString(), pathElements, pathIndices: [0, 0, 0, 0],
};
const proof = await createZkProofService().generateProof(witness);
const array = (values: string[]) => `[${values.map(v => `uint256(${v})`).join(", ")}]`;
writeFileSync(join(import.meta.dir, "../../../sc/test/ContributionProofFixture.sol"), `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
// Generated by backend/src/scripts/zk-fixture.ts. Synthetic public fixture, never a donor witness.
abstract contract ContributionProofFixture {
    bytes32 constant BATCH_ROOT = ${toFieldHex(BigInt(witness.batchRoot))};
    bytes32 constant RECEIPT_COMMITMENT = ${toFieldHex(BigInt(witness.receiptCommitment))};
    uint256[2] a; uint256[2][2] b; uint256[2] c; uint256[5] pubSignals;
    function loadFixture() internal {
        a = ${array(proof.calldata.a)};
        b = [${proof.calldata.b.map(array).join(", ")}];
        c = ${array(proof.calldata.c)};
        pubSignals = ${array(proof.calldata.input)};
    }
}
`);
