// Convert a snarkjs `verification_key.json` (Groth16, BN254) into the Rust
// constant that the on-chain verifier expects, ready to paste into
// `zkt_core/src/instructions/donate_zk.rs`.
//
//   node vk_to_rust.js verification_key.json
//
// Emits, to stdout, a `VK_IC` array + a `VERIFYING_KEY = Some(...)` block.
// Byte layout matches `zkt_core/src/groth16.rs`:
//   * G1 points → 64 bytes, big-endian x ++ y
//   * G2 points → 128 bytes, big-endian, Fp2 components reversed to [c1, c0]
//     (the EVM / arkworks ordering), i.e. x_c1 ++ x_c0 ++ y_c1 ++ y_c0
//
// This mirrors Light Protocol's parse_vk_to_rust.js, which our verifier is
// vendored from. See solana/circuits/CEREMONY.md.

const fs = require('fs');
const { utils } = require('ffjavascript');
const { unstringifyBigInts, leInt2Buff } = utils;

const path = process.argv[2];
if (!path) {
  console.error('usage: node vk_to_rust.js <verification_key.json>');
  process.exit(1);
}

// decimal string -> 32 big-endian bytes
const be = (s) => Array.from(leInt2Buff(unstringifyBigInts(s), 32)).reverse();
const g1 = (p) => be(p[0]).concat(be(p[1])); // x || y                 (64)
const g2 = (p) =>
  be(p[0][1]).concat(be(p[0][0])) //          x_c1 || x_c0
    .concat(be(p[1][1])).concat(be(p[1][0])); // y_c1 || y_c0          (128)
const row = (a) => a.join(', ');

const vk = JSON.parse(fs.readFileSync(path));
const n = vk.IC.length;

let s = '';
s += `// Generated by vk_to_rust.js from ${path} — DO NOT hand-edit.\n`;
s += `// nr_pubinputs = vk_ic.len() = ${n} (1 circuit output + ${n - 1} public inputs).\n`;
s += `const VK_IC: [[u8; 64]; ${n}] = [\n`;
for (const ic of vk.IC) s += `    [${row(g1(ic))}],\n`;
s += `];\n`;
s += `const VERIFYING_KEY: Option<Groth16Verifyingkey<'static>> = Some(Groth16Verifyingkey {\n`;
s += `    nr_pubinputs: ${n},\n`;
s += `    vk_alpha_g1: [${row(g1(vk.vk_alpha_1))}],\n`;
s += `    vk_beta_g2: [${row(g2(vk.vk_beta_2))}],\n`;
s += `    vk_gamme_g2: [${row(g2(vk.vk_gamma_2))}],\n`;
s += `    vk_delta_g2: [${row(g2(vk.vk_delta_2))}],\n`;
s += `    vk_ic: &VK_IC,\n`;
s += `});\n`;

process.stdout.write(s);
