"use strict";
const fs = require("node:fs");
const path = require("node:path");
const { createRequire } = require("node:module");
const { execFileSync } = require("node:child_process");
const { assertNode, cleanEnv } = require("./release-lib.cjs");
async function smoke(root) {
  assertNode();
  const runner = path.join(root, "backend/dist/zk-prover-runner.cjs");
  const fromRunner = createRequire(runner);
  const { buildPoseidon } = fromRunner("circomlibjs");
  const snarkjs = fromRunner("snarkjs");
  const poseidon = await buildPoseidon();
  const hash = values => poseidon.F.toString(poseidon(values.map(BigInt)));
  // Entirely synthetic, generated in memory; never read DB, env, or fixture witness.
  const contributionIdHash = "11", amount = "100", salt = "22", fundType = "1", purposeHash = "33", institutionKey = "44";
  const leaf = hash([contributionIdHash, amount, salt, fundType, purposeHash]);
  const receiptCommitment = hash([institutionKey, contributionIdHash, leaf]);
  const pathElements = ["0", "0", "0", "0"];
  let batchRoot = leaf;
  for (const sibling of pathElements) batchRoot = hash([batchRoot, sibling]);
  const input = { batchRoot, receiptCommitment, institutionKey, contributionIdHash, fundType, amount, salt, purposeHash, pathElements, pathIndices: ["0", "0", "0", "0"] };
  const scratch = path.join(root, ".scratch");
  fs.mkdirSync(scratch, { recursive: true });
  if (fs.realpathSync(scratch) !== scratch) throw new Error("Smoke scratch directory must not be a symlink.");
  const dir = fs.mkdtempSync(path.join(scratch, "proof-smoke-"));
  const inputPath = path.join(dir, "input.json"), outputPath = path.join(dir, "output.json");
  try {
    fs.writeFileSync(inputPath, JSON.stringify(input), { mode: 0o600, flag: "wx" });
    execFileSync("node", [runner, inputPath, path.join(root, "sc/circuits/build/contribution_membership_js/contribution_membership.wasm"), path.join(root, "sc/circuits/build/circuit_final.zkey"), outputPath], { env: cleanEnv(), timeout: 120000, stdio: "pipe" });
    const result = JSON.parse(fs.readFileSync(outputPath, "utf8"));
    const expected = [batchRoot, receiptCommitment, institutionKey, contributionIdHash, fundType];
    if (JSON.stringify(result.publicSignals) !== JSON.stringify(expected)) throw new Error("Synthetic public statement mismatch.");
    if (result.calldata?.input?.length !== 5 || result.calldata.input.some((value, index) => BigInt(value) !== BigInt(expected[index]))) throw new Error("Synthetic calldata mismatch.");
    const vk = JSON.parse(fs.readFileSync(path.join(root, "sc/circuits/build/verification_key.json"), "utf8"));
    if (!await snarkjs.groth16.verify(vk, result.publicSignals, result.proof)) throw new Error("Synthetic proof verification failed.");
    console.log("Offline synthetic Groth16 proof: generated by shipped runner and verified against pinned verification key.");
  } finally {
    for (const file of [inputPath, outputPath]) { if (fs.existsSync(file)) fs.unlinkSync(file); }
    fs.rmdirSync(dir);
  }
}
if (require.main === module) {
  if (process.argv.length !== 3) { console.error("Internal helper: use node deploy/preflight-backend.cjs --smoke"); process.exit(1); }
  smoke(path.resolve(process.argv[2])).then(() => process.exit(0), () => { console.error("Offline synthetic proof smoke failed (no witness logged)."); process.exit(1); });
}
module.exports = { smoke };
