// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
// Generated by backend/src/scripts/zk-fixture.ts. Synthetic public fixture, never a donor witness.
abstract contract ContributionProofFixture {
    bytes32 constant BATCH_ROOT = 0x1330c292d27210ee13970af4c762a0563cbb68a00bbfc6ebb787d2d5fbad4f92;
    bytes32 constant RECEIPT_COMMITMENT = 0x13dc7ef2dd33487a8eac0be3276240b39f828bdc7abf13190d5dc3d6d5265dbe;
    uint256[2] a; uint256[2][2] b; uint256[2] c; uint256[5] pubSignals;
    function loadFixture() internal {
        a = [uint256(0x1e465ee1950ac3a29b9400a140c5a9bb6d57b68ce2c97da6605e19e25aebee78), uint256(0x2dec46815fbb19ffd16a065f490bb1efc4cd93fc4d3f8b39173bb12c87c193da)];
        b = [[uint256(0x1761e2ef5f49810d74761eacf8767f7367d2b43eddbb8f88f93b3875308c20df), uint256(0x044ad45849cdc193e80f6c657700b548f5e76229dacb11d8778caa1175313bad)], [uint256(0x17cfec1d25debbf752d3009c2b180b9034194670beea97ead9dbc422fd6a89b3), uint256(0x0fb3100877128898f762a4b7d55db7e30fd3d39a4091e78afc8a27528319343a)]];
        c = [uint256(0x199f0512fe9b1a4332c3ad51030bb71b9569cbb13e25d0f11036ee11a137cd68), uint256(0x2af3a9a9ee2d0235f9f2430762c958cc61f38b9883d7b6eaae4b7b833a8ef7cb)];
        pubSignals = [uint256(0x1330c292d27210ee13970af4c762a0563cbb68a00bbfc6ebb787d2d5fbad4f92), uint256(0x13dc7ef2dd33487a8eac0be3276240b39f828bdc7abf13190d5dc3d6d5265dbe), uint256(0x1e621673f21549be0c2ee015bb3514a01ada60b1d5e36a2e08b26677c211e2d1), uint256(0x0314e11b50cea6399059aab8d46065953737aa56039099116a974fbf34f1403a), uint256(0x0000000000000000000000000000000000000000000000000000000000000000)];
    }
}
