/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DonasiRouteImport } from './routes/donasi'
import { Route as LaporanPeriodeRouteImport } from './routes/laporan-periode'
import { Route as RekonsiliasiRouteImport } from './routes/rekonsiliasi'
import { Route as RuangKerjaRouteImport } from './routes/ruang-kerja'
import { Route as SertifikatRouteImport } from './routes/sertifikat'
import { Route as TransparansiRouteImport } from './routes/transparansi'
import { Route as VerifikasiRouteImport } from './routes/verifikasi'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as TransparansiBuktiRouteImport } from './routes/transparansi/bukti'
import { Route as TransparansiLaporanRouteImport } from './routes/transparansi/laporan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiRoute = DonasiRouteImport.update({
  id: '/donasi',
  path: '/donasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanPeriodeRoute = LaporanPeriodeRouteImport.update({
  id: '/laporan-periode',
  path: '/laporan-periode',
  getParentRoute: () => rootRouteImport,
} as any)
const RekonsiliasiRoute = RekonsiliasiRouteImport.update({
  id: '/rekonsiliasi',
  path: '/rekonsiliasi',
  getParentRoute: () => rootRouteImport,
} as any)
const RuangKerjaRoute = RuangKerjaRouteImport.update({
  id: '/ruang-kerja',
  path: '/ruang-kerja',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikatRoute = SertifikatRouteImport.update({
  id: '/sertifikat',
  path: '/sertifikat',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparansiRoute = TransparansiRouteImport.update({
  id: '/transparansi',
  path: '/transparansi',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifikasiRoute = VerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparansiBuktiRoute = TransparansiBuktiRouteImport.update({
  id: '/bukti',
  path: '/bukti',
  getParentRoute: () => TransparansiRoute,
} as any)
const TransparansiLaporanRoute = TransparansiLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => TransparansiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donasi': typeof DonasiRoute
  '/laporan-periode': typeof LaporanPeriodeRoute
  '/rekonsiliasi': typeof RekonsiliasiRoute
  '/ruang-kerja': typeof RuangKerjaRoute
  '/sertifikat': typeof SertifikatRoute
  '/transparansi': typeof TransparansiRouteWithChildren
  '/verifikasi': typeof VerifikasiRoute
  '/admin/roles': typeof AdminRolesRoute
  '/transparansi/bukti': typeof TransparansiBuktiRoute
  '/transparansi/laporan': typeof TransparansiLaporanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donasi': typeof DonasiRoute
  '/laporan-periode': typeof LaporanPeriodeRoute
  '/rekonsiliasi': typeof RekonsiliasiRoute
  '/ruang-kerja': typeof RuangKerjaRoute
  '/sertifikat': typeof SertifikatRoute
  '/transparansi': typeof TransparansiRouteWithChildren
  '/verifikasi': typeof VerifikasiRoute
  '/admin/roles': typeof AdminRolesRoute
  '/transparansi/bukti': typeof TransparansiBuktiRoute
  '/transparansi/laporan': typeof TransparansiLaporanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donasi': typeof DonasiRoute
  '/laporan-periode': typeof LaporanPeriodeRoute
  '/rekonsiliasi': typeof RekonsiliasiRoute
  '/ruang-kerja': typeof RuangKerjaRoute
  '/sertifikat': typeof SertifikatRoute
  '/transparansi': typeof TransparansiRouteWithChildren
  '/verifikasi': typeof VerifikasiRoute
  '/admin/roles': typeof AdminRolesRoute
  '/transparansi/bukti': typeof TransparansiBuktiRoute
  '/transparansi/laporan': typeof TransparansiLaporanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donasi'
    | '/laporan-periode'
    | '/rekonsiliasi'
    | '/ruang-kerja'
    | '/sertifikat'
    | '/transparansi'
    | '/verifikasi'
    | '/admin/roles'
    | '/transparansi/bukti'
    | '/transparansi/laporan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donasi'
    | '/laporan-periode'
    | '/rekonsiliasi'
    | '/ruang-kerja'
    | '/sertifikat'
    | '/transparansi'
    | '/verifikasi'
    | '/admin/roles'
    | '/transparansi/bukti'
    | '/transparansi/laporan'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donasi'
    | '/laporan-periode'
    | '/rekonsiliasi'
    | '/ruang-kerja'
    | '/sertifikat'
    | '/transparansi'
    | '/verifikasi'
    | '/admin/roles'
    | '/transparansi/bukti'
    | '/transparansi/laporan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonasiRoute: typeof DonasiRoute
  LaporanPeriodeRoute: typeof LaporanPeriodeRoute
  RekonsiliasiRoute: typeof RekonsiliasiRoute
  RuangKerjaRoute: typeof RuangKerjaRoute
  SertifikatRoute: typeof SertifikatRoute
  TransparansiRoute: typeof TransparansiRouteWithChildren
  VerifikasiRoute: typeof VerifikasiRoute
  AdminRolesRoute: typeof AdminRolesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi': {
      id: '/donasi'
      path: '/donasi'
      fullPath: '/donasi'
      preLoaderRoute: typeof DonasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan-periode': {
      id: '/laporan-periode'
      path: '/laporan-periode'
      fullPath: '/laporan-periode'
      preLoaderRoute: typeof LaporanPeriodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekonsiliasi': {
      id: '/rekonsiliasi'
      path: '/rekonsiliasi'
      fullPath: '/rekonsiliasi'
      preLoaderRoute: typeof RekonsiliasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruang-kerja': {
      id: '/ruang-kerja'
      path: '/ruang-kerja'
      fullPath: '/ruang-kerja'
      preLoaderRoute: typeof RuangKerjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifikat': {
      id: '/sertifikat'
      path: '/sertifikat'
      fullPath: '/sertifikat'
      preLoaderRoute: typeof SertifikatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparansi': {
      id: '/transparansi'
      path: '/transparansi'
      fullPath: '/transparansi'
      preLoaderRoute: typeof TransparansiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifikasi': {
      id: '/verifikasi'
      path: '/verifikasi'
      fullPath: '/verifikasi'
      preLoaderRoute: typeof VerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparansi/bukti': {
      id: '/transparansi/bukti'
      path: '/bukti'
      fullPath: '/transparansi/bukti'
      preLoaderRoute: typeof TransparansiBuktiRouteImport
      parentRoute: typeof TransparansiRoute
    }
    '/transparansi/laporan': {
      id: '/transparansi/laporan'
      path: '/laporan'
      fullPath: '/transparansi/laporan'
      preLoaderRoute: typeof TransparansiLaporanRouteImport
      parentRoute: typeof TransparansiRoute
    }
  }
}

interface TransparansiRouteChildren {
  TransparansiBuktiRoute: typeof TransparansiBuktiRoute
  TransparansiLaporanRoute: typeof TransparansiLaporanRoute
}

const TransparansiRouteChildren: TransparansiRouteChildren = {
  TransparansiBuktiRoute: TransparansiBuktiRoute,
  TransparansiLaporanRoute: TransparansiLaporanRoute,
}

const TransparansiRouteWithChildren = TransparansiRoute._addFileChildren(
  TransparansiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonasiRoute: DonasiRoute,
  LaporanPeriodeRoute: LaporanPeriodeRoute,
  RekonsiliasiRoute: RekonsiliasiRoute,
  RuangKerjaRoute: RuangKerjaRoute,
  SertifikatRoute: SertifikatRoute,
  TransparansiRoute: TransparansiRouteWithChildren,
  VerifikasiRoute: VerifikasiRoute,
  AdminRolesRoute: AdminRolesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
