// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.31;

/**
 * @title HonkVerifier
 * @notice Interface for the UltraHONK proof verifier deployed on-chain.
 * @dev The actual verifier contract is generated by Barretenberg's
 *      `bb write_solidity_verifier` and deployed separately due to its
 *      large code size (~34 KB runtime, 2,461 lines).
 *      This interface provides the ABI needed by ZKTCore to call verify().
 */
interface IHonkVerifier {
    /**
     * @notice Verify an UltraHONK proof
     * @param proof The proof bytes (msgpack format, ~8 KB)
     * @param publicInputs Array of public inputs (field elements as bytes32)
     * @return True if the proof is valid
     */
    function verify(bytes calldata proof, bytes32[] calldata publicInputs)
        external returns (bool);
}

/**
 * @title HonkVerifier
 * @notice ABI-only stub. Deploying this gives you a NON-FUNCTIONAL verifier.
 *
 * @dev  ############################################################
 *       #  `new HonkVerifier()` DOES NOT DEPLOY A REAL VERIFIER.   #
 *       #  verify() returns false, so every proof-gated call        #
 *       #  reverts. This is fail-closed, and it is deliberate.      #
 *       ############################################################
 *
 *       This contract exists to give ZKTCore a type-safe ABI. It is 255 bytes
 *       of init bytecode; the real Barretenberg verifier is 33,880 bytes of
 *       deployed bytecode (sc/script/artifacts/HonkVerifier.json), which
 *       EXCEEDS the EIP-170 limit of 24,576 bytes and therefore cannot be
 *       deployed as a single contract. Splitting it, or a proxy/delegatecall
 *       layout, is required before donateZK/donateZKPrivate can work.
 *
 *       Consequence today: ZKTCore.donateZK and ZKTCore.donateZKPrivate always
 *       revert with "Invalid ZK proof". That is the correct failure mode — do
 *       not "fix" it by making verify() return true.
 */
contract HonkVerifier is IHonkVerifier {
    /**
     * @notice Whether this is a working verifier.
     * @dev Always false for this stub. Deploy scripts should assert on it
     *      rather than assuming a deployed address means a usable verifier.
     */
    function isOperational() external pure virtual returns (bool) {
        return false;
    }

    /// @inheritdoc IHonkVerifier
    /// @dev Fails closed. Overridden only by a real generated verifier.
    function verify(bytes calldata, /* proof */ bytes32[] calldata /* publicInputs */)
        external view virtual returns (bool) {
        return false;
    }
}
